builds:
- env:
  - CGO_ENABLED=0
  main: main.go
  binary: packer-provisioner-puppet-bolt
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64