builds:
- env:
  - CGO_ENABLED=0
  main: main.go
  binary: packer-provisioner-puppet-bolt
  goarch:
    - amd64
    - arm
    - arm64
    - 386
  goos:
    - freebsd
    - windows
    - linux
    - darwin

archives:
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64