language: go
go:
  - 1.12.7
env: 
  - GO111MODULE=on
install: true
gobuild_args: -mod=vendor
script: go test -v ./...
after_success:
- test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash