language: go

go:
  - 1.12.x

env:
  - GO111MODULE=on

before_install:
  - go get github.com/mattn/goveralls
script:
  - $HOME/gopath/bin/goveralls -v -service=travis-ci
  - "make test"

after_success:
- test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash